server:
  port: ${SERVER_PORT:8090}
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/client_user?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DB_USER:root}
    password: ${DB_PASS:Qw123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    open-in-view: false
    database: MYSQL
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/liquibase/liquibase-changeLog.xml
